server:
    port: 8083

spring:
  cloud:
    gateway:
      routes:
        ## crud endpoints
        - id: patient-service-route
          uri: http://patient-service:8080
          predicates: ## matches with the request sent to gateway
            - Path=/api/patients/**
          filters: ## get rid of first prefix api/ 
            - StripPrefix=1 
        
        ## docs endpoints
        - id: api-docs-patient-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api-docs/patients/**
          filters: ## rewrite req to get rid of /api-docs/patients and map it to /v3/api-docs
            - RewritePath=/api-docs/patients, /v3/api-docs